package es.fplumara.dam1.alumnos.repository;

import es.fplumara.dam1.alumnos.model.Alumno;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

public class AlumnoRepositoryDB implements AlumnoRepository {

    private Connection getConnection() throws SQLException {
        String url  = System.getenv().getOrDefault("JDBC_URL",
                "jdbc:postgresql://localhost:5432/dam1");
        String user = System.getenv().getOrDefault("JDBC_USER", "dam1");
        String pass = System.getenv().getOrDefault("JDBC_PASSWORD", "dam1");

        return DriverManager.getConnection(url, user, pass);
    }

    /**
     * Crea la tabla si no existe
     */
    public void initSchema() {
        String ddl = """
                CREATE TABLE IF NOT EXISTS alumnos (
                  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  nombre VARCHAR(100) NOT NULL,
                  apellidos VARCHAR(150) NOT NULL,
                  anio_nacimiento INT NOT NULL
                );
                """;

        try {
            Connection c = getConnection();
            Statement st = c.createStatement();
            st.execute(ddl);
        } catch (SQLException e) {
            throw new RuntimeException("Error inicializando schema", e);
        }
    }

    @Override
    public Optional<Alumno> findById(Integer id) {
        if (id == null) {
            return Optional.empty();
        }

        String sql = "SELECT id, nombre, apellidos, anio_nacimiento FROM alumnos WHERE id = ?";

        try {
            Connection c = getConnection();
            PreparedStatement ps = c.prepareStatement(sql);
            ps.setInt(1, id);
            ResultSet rs = ps.executeQuery();
            if (!rs.next()) {
                return Optional.empty();
            }
            return Optional.of(mapAlumno(rs));
        } catch (SQLException e) {
            throw new RuntimeException("Error buscando alumno por id " + id, e);
        }
    }

    @Override
    public List<Alumno> findAll() {
        String sql = "SELECT id, nombre, apellidos, anio_nacimiento FROM alumnos ORDER BY id";

        try {
            Connection c = getConnection();
            PreparedStatement ps = c.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            List<Alumno> out = new ArrayList<>();
            while (rs.next()) {
                out.add(mapAlumno(rs));
            }
            return out;

        } catch (SQLException e) {
            throw new RuntimeException("Error listando alumnos", e);
        }
    }

    @Override
    public Alumno insert(Alumno alumno) {
        if (alumno == null) throw new IllegalArgumentException("El alumno no puede ser null");

        String sql = "INSERT INTO alumnos (nombre, apellidos, anio_nacimiento) VALUES (?, ?, ?)";

        try (Connection c = getConnection(); PreparedStatement ps = c.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

            ps.setString(1, alumno.getNombre());
            ps.setString(2, alumno.getApellidos());
            ps.setInt(3, alumno.getAnioNacimiento());

            ps.executeUpdate();

            ResultSet keys = ps.getGeneratedKeys();
            if (keys.next()) {
                alumno.setId(keys.getInt(1));
            }


            return alumno;

        } catch (SQLException e) {
            throw new RuntimeException("Error insertando alumno", e);
        }
    }

    @Override
    public Alumno update(Alumno alumno) {
        if (alumno == null) throw new IllegalArgumentException("El alumno no puede ser null");
        if (alumno.getId() == null || alumno.getId() <= 0) {
            throw new IllegalArgumentException("El id debe ser un entero positivo");
        }

        String sql = "UPDATE alumnos SET nombre=?, apellidos=?, anio_nacimiento=? WHERE id=?";

        try {
            Connection c = getConnection();
            PreparedStatement ps = c.prepareStatement(sql);

            ps.setString(1, alumno.getNombre());
            ps.setString(2, alumno.getApellidos());
            ps.setInt(3, alumno.getAnioNacimiento());
            ps.setInt(4, alumno.getId());

            int updated = ps.executeUpdate();
            if (updated == 0) {
                throw new IllegalArgumentException("No existe alumno con id " + alumno.getId());
            }

            return alumno;

        } catch (SQLException e) {
            throw new RuntimeException("Error actualizando alumno con id " + alumno.getId(), e);
        }
    }

    private Alumno mapAlumno(ResultSet rs) throws SQLException {
        return new Alumno(
                rs.getInt("id"),
                rs.getString("nombre"),
                rs.getString("apellidos"),
                rs.getInt("anio_nacimiento")
        );
    }
}